service: cinchAPI

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  role: arn:aws:iam::420664280170:role/CinchLambda
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
